// <auto-generated />
namespace Hiper.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class shareProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shareProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201512291016519_shareProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
